name: Deploy to Development

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Build and Publish
        run: |
          cd minimal-api
          dotnet restore
          dotnet publish -c Release -o published

      - name: Zip the published files
        run: |
          cd minimal-api/published
          zip -r ../minimal-api.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: minimal-api/minimal-api.zip

  deploy:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ./published/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID1 }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az webapp deploy --resource-group declerck-rg-dev-westeurope \
                              --name declerck-as-dev-westeurope \
                              --src-path ./published/minimal-api.zip \
                              --type zip
